[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Redirect all requests to Next.js (simplified)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 